### PR TITLE
Alexkbranch1matplotlib

### PR DESCRIPTION
**Pull request by alexkdsm**
Moved the code to notebooks

### CODE REVIEW

**Comment by rbschoop** [comment]
Hi Alex, 
you moved the .py Code to the Folder Notebooks, but I think what Cor meant is "move it to a .ipynb file…

**Comment by alexkdsm** [comment]
> Hi Alex,
> you moved the .py Code to the Folder Notebooks, but I think what Cor meant is "move it to a .ipynb file…

well we discussed about the "data science" folder and that he would keep files like the one I made separately. It made sense that he referred to the folder ?

**Comment by rbschoop** [comment]
Yes, Keep it in the Notebook folder, but rename the file as a jupyter notebook...

**Comment by JCZuurmond** [comment]
Yes, I am ok with both! Ready to merge if you would like to keep the `.py` file or move it into a notebook.

@alexkdsm

**Pull request merged**
